#!/usr/bin/env python3
"""Snapshot the retained openami/<device>/meter_* MQTT topics into include/meter_snapshot.h.

The firmware sends this JSON from server to client over SPI. Re-run this script
to refresh the hardcoded payload:

    pip install paho-mqtt
    python3 tools/snapshot_meters.py

The output is one JSON object keyed by topic suffix, with each topic's payload
embedded verbatim:  {"meter_0":{...},"meter_1":{...},...}
"""

import argparse
import datetime
import json
import pathlib
import re
import sys
import time

import paho.mqtt.client as mqtt

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--host", default="public.cloud.shiftr.io")
    ap.add_argument("--port", type=int, default=1883)
    ap.add_argument("--user", default="public")
    ap.add_argument("--password", default="public")
    ap.add_argument("--device", default="StreetEMS_A779A8")
    ap.add_argument("--wait", type=float, default=5.0, help="seconds to collect messages")
    ap.add_argument("--out", default=str(ROOT / "include" / "meter_snapshot.h"))
    args = ap.parse_args()

    prefix = f"openami/{args.device}/"
    payloads = {}

    def on_connect(client, userdata, flags, reason_code, properties=None):
        client.subscribe(prefix + "+")

    def on_message(client, userdata, msg):
        name = msg.topic[len(prefix):]
        if name.startswith("meter_"):
            payloads[name] = msg.payload.decode("utf-8")

    client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2)
    client.username_pw_set(args.user, args.password)
    client.on_connect = on_connect
    client.on_message = on_message
    client.connect(args.host, args.port, 30)
    client.loop_start()
    time.sleep(args.wait)
    client.loop_stop()
    client.disconnect()

    if not payloads:
        sys.exit(f"no {prefix}meter_* messages received in {args.wait}s")

    def natural(name):
        return [int(p) if p.isdigit() else p for p in re.split(r"(\d+)", name)]

    names = sorted(payloads, key=natural)
    for n in names:
        json.loads(payloads[n])  # each payload must be valid JSON to embed verbatim
    snapshot = "{" + ",".join(f'"{n}":{payloads[n]}' for n in names) + "}"
    json.loads(snapshot)
    if ")JSON\"" in snapshot:
        sys.exit("payload contains the raw-string delimiter )JSON\"")

    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    header = f"""// Generated by tools/snapshot_meters.py -- do not edit by hand.
// Source: mqtt://{args.host}:{args.port} {prefix}meter_*
// Captured: {stamp}
// Topics: {", ".join(names)}
// Size: {len(snapshot)} bytes
#pragma once

static const char METER_SNAPSHOT_JSON[] = R"JSON({snapshot})JSON";
"""
    pathlib.Path(args.out).write_text(header)
    print(f"wrote {args.out}: {len(names)} topics, {len(snapshot)} bytes")


if __name__ == "__main__":
    main()
